quote_controller:
    resource:
        path: '../src/Recommendation/Infrastructure/Symfony/Controller/'
        namespace: CourseBundle\Recommendation\Infrastructure\Symfony\Controller
    type: attribute
    name_prefix: 'api_'
